#!/bin/sh

command="$1"
shift 1

if [ -d "$NIKA_SCRIPT_LIBEXEC_DIRECTORY/$command" ]; then
  . "$NIKA_SCRIPT_LIBEXEC_DIRECTORY/$command/_main" "$@"
else
  . "$NIKA_SCRIPT_LIBEXEC_DIRECTORY/$command" "$@"
fi

